name: Deploy Package
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Testing code..."
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: astral-sh/setup-uv@v4
      - run: uv sync
      - run: uv build
      - shell: bash
        env:
          UV_PUBLISH_TOKEN: ${{secrets.PYPI_TOKEN }}
          UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
        run: uv publish
