name: Release Package
on:
  push:
    branches:
      - main
      - dev
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+a[0-9]'
      - '[0-9]+.[0-9]+.[0-9]+b[0-9]'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]'
env:
  PACKAGE_NAME: 'qtmvvmtoolkit'
  OWNER: 'victor3spoir'

jobs:
  details:
    runs-on: ubuntu-22.04
    outputs:
      new_version: ${{ steps.release.outputs.new_version}}
      suffix: ${{ steps.release.outputs.suffix}}
      tag_name: ${{ steps.release.outputs.tag_name}}
    steps:
      - run: echo "Testing"
  check_pypi:
    runs-on: ubuntu-22.04
    needs:
      - details
    steps:
      - run: echo "Checking Pypi"

  build_deploy:
    runs-on: ubuntu-22.04
    needs:
      - details
      - check_pypi
    steps:
      - run: echo "Testing code..."
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: astral-sh/setup-uv@v4
      - run: uv sync
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

